
import { IOption } from 'ng-select';

export const myOptionsPaises: Array<IOption> = [
    { label: 'África do Sul', value: 'África do Sul' },
    { label: 'Albânia', value: 'Albânia' },
    { label: 'Alemania', value: 'Alemania' },
    { label: 'Andorra', value: 'Andorra' },
    { label: 'Angola', value: 'Angola' },
    { label: 'Anguilla', value: 'Anguilla' },
    { label: 'Antigua', value: 'Antigua' },
    { label: 'Arábia Saudita', value: 'Arábia Saudita' },
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Armênia', value: 'Armênia' },
    { label: 'Aruba', value: 'Aruba' },
    { label: 'Austrália', value: 'Austrália' },
    { label: 'Áustria', value: 'Áustria' },
    { label: 'Azerbaijão', value: 'Azerbaijão' },
    { label: 'Bahamas', value: 'Bahamas' },
    { label: 'Bahrein', value: 'Bahrein' },
    { label: 'Bangladesh', value: 'Bangladesh' },
    { label: 'Barbados', value: 'Barbados' },
    { label: 'Bélgica', value: 'Bélgica' },
    { label: 'Benin', value: 'Benin' },
    { label: 'Bermudas', value: 'Bermudas' },
    { label: 'Botsuana', value: 'Botsuana' },
    { label: 'Brasil', value: 'Brasil' },
    { label: 'Brunei', value: 'Brunei' },
    { label: 'Bulgária', value: 'Bulgária' },
    { label: 'Burkina Fasso', value: 'Burkina Fasso' },
    { label: 'botão', value: 'botão' },
    { label: 'Cabo Verde', value: 'Cabo Verde' },
    { label: 'Camarões', value: 'Camarões' },
    { label: 'Camboja', value: 'Camboja' },
    { label: 'Canadá', value: 'Canadá' },
    { label: 'Cazaquistão', value: 'Cazaquistão' },
    { label: 'Chade', value: 'Chade' },
    { label: 'Chile', value: 'Chile' },
    { label: 'China', value: 'China' },
    { label: 'Cidade do Vaticano', value: 'Cidade do Vaticano' },
    { label: 'Colômbia', value: 'Colômbia' },
    { label: 'Congo', value: 'Congo' },
    { label: 'Coréia do Sul', value: 'Coréia do Sul' },
    { label: 'Costa do Marfim', value: 'Costa do Marfim' },
    { label: 'Costa Rica', value: 'Costa Rica' },
    { label: 'Croácia', value: 'Croácia' },
    { label: 'Dinamarca', value: 'Dinamarca' },
    { label: 'Djibuti', value: 'Djibuti' },
    { label: 'Dominica', value: 'Dominica' },
    { label: 'EUA', value: 'EUA' },
    { label: 'Egito', value: 'Egito' },
    { label: 'El Salvador', value: 'El Salvador' },
    { label: 'Emirados Árabes', value: 'Emirados Árabes' },
    { label: 'Equador', value: 'Equador' },
    { label: 'Eritréia', value: 'Eritréia' },
    { label: 'Escócia', value: 'Escócia' },
    { label: 'Eslováquia', value: 'Eslováquia' },
    { label: 'Eslovênia', value: 'Eslovênia' },
    { label: 'Espanha', value: 'Espanha' },
    { label: 'Estônia', value: 'Estônia' },
    { label: 'Etiópia', value: 'Etiópia' },
    { label: 'Fiji', value: 'Fiji' },
    { label: 'Filipinas', value: 'Filipinas' },
    { label: 'Finlândia', value: 'Finlândia' },
    { label: 'França', value: 'França' },
    { label: 'Gabão', value: 'Gabão' },
    { label: 'Gâmbia', value: 'Gâmbia' },
    { label: 'Gana', value: 'Gana' },
    { label: 'Geórgia', value: 'Geórgia' },
    { label: 'Gibraltar', value: 'Gibraltar' },
    { label: 'Granada', value: 'Granada' },
    { label: 'Grécia', value: 'Grécia' },
    { label: 'Guadalupe', value: 'Guadalupe' },
    { label: 'Guam', value: 'Guam' },
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Guiana', value: 'Guiana' },
    { label: 'Guiana Francesa', value: 'Guiana Francesa' },
    { label: 'Guiné-bissau', value: 'Guiné-bissau' },
    { label: 'Haiti', value: 'Haiti' },
    { label: 'Holanda', value: 'Holanda' },
    { label: 'Honduras', value: 'Honduras' },
    { label: 'Hong Kong', value: 'Hong Kong' },
    { label: 'Hungria', value: 'Hungria' },
    { label: 'Iêmen', value: 'Iêmen' },
    { label: 'Ilhas Cayman', value: 'Ilhas Cayman' },
    { label: 'Ilhas Cook', value: 'Ilhas Cook' },
    { label: 'Ilhas Curaçao', value: 'Ilhas Curaçao' },
    { label: 'Ilhas Marshall', value: 'Ilhas Marshall' },
    { label: 'Ilhas Turks & Caicos', value: 'Ilhas Turks & Caicos' },
    { label: 'Ilhas Virgens (brit.)', value: 'Ilhas Virgens (brit.)' },
    { label: 'Ilhas Virgens(amer.)', value: 'Ilhas Virgens(amer.)' },
    { label: 'Ilhas Wallis e Futuna', value: 'Ilhas Wallis e Futuna' },
    { label: 'Índia', value: 'Índia' },
    { label: 'Indonésia', value: 'Indonésia' },
    { label: 'Inglaterra', value: 'Inglaterra' },
    { label: 'Irlanda', value: 'Irlanda' },
    { label: 'Islândia', value: 'Islândia' },
    { label: 'Israel', value: 'Israel' },
    { label: 'Itália', value: 'Itália' },
    { label: 'Jamaica', value: 'Jamaica' },
    { label: 'Japão', value: 'Japão' },
    { label: 'Jordânia', value: 'Jordânia' },
    { label: 'Kuwait', value: 'Kuwait' },
    { label: 'Latvia', value: 'Latvia' },
    { label: 'Líbano', value: 'Líbano' },
    { label: 'Liechtenstein', value: 'Liechtenstein' },
    { label: 'Lituânia', value: 'Lituânia' },
    { label: 'Luxemburgo', value: 'Luxemburgo' },
    { label: 'Macau', value: 'Macau' },
    { label: 'Macedônia', value: 'Macedônia' },
    { label: 'Madagascar', value: 'Madagascar' },
    { label: 'Malásia', value: 'Malásia' },
    { label: 'Malaui', value: 'Malaui' },
    { label: 'Mali', value: 'Mali' },
    { label: 'Malta', value: 'Malta' },
    { label: 'Marrocos', value: 'Marrocos' },
    { label: 'Martinica', value: 'Martinica' },
    { label: 'Mauritânia', value: 'Mauritânia' },
    { label: 'Mauritius', value: 'Mauritius' },
    { label: 'México', value: 'México' },
    { label: 'Moldova', value: 'Moldova' },
    { label: 'Mônaco', value: 'Mônaco' },
    { label: 'Montserrat', value: 'Montserrat' },
    { label: 'Nepal', value: 'Nepal' },
    { label: 'Nicarágua', value: 'Nicarágua' },
    { label: 'Niger', value: 'Niger' },
    { label: 'Nigéria', value: 'Nigéria' },
    { label: 'Noruega', value: 'Noruega' },
    { label: 'Nova Caledônia', value: 'Nova Caledônia' },
    { label: 'Nova Zelândia', value: 'Nova Zelândia' },
    { label: 'Omã', value: 'Omã' },
    { label: 'Palau', value: 'Palau' },
    { label: 'Panamá', value: 'Panamá' },
    { label: 'Papua-nova Guiné', value: 'Papua-nova Guiné' },
    { label: 'Paquistão', value: 'Paquistão' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Polinésia Francesa', value: 'Polinésia Francesa' },
    { label: 'Polônia', value: 'Polônia' },
    { label: 'Porto Rico', value: 'Porto Rico' },
    { label: 'Portugal', value: 'Portugal' },
    { label: 'Qatar', value: 'Qatar' },
    { label: 'Quênia', value: 'Quênia' },
    { label: 'Rep. Dominicana', value: 'Rep. Dominicana' },
    { label: 'Rep. Tcheca', value: 'Rep. Tcheca' },
    { label: 'Reunion', value: 'Reunion' },
    { label: 'Romênia', value: 'Romênia' },
    { label: 'Ruanda', value: 'Ruanda' },
    { label: 'Rússia', value: 'Rússia' },
    { label: 'Saipan', value: 'Saipan' },
    { label: 'Samoa Americana', value: 'Samoa Americana' },
    { label: 'Senegal', value: 'Senegal' },
    { label: 'Serra Leone', value: 'Serra Leone' },
    { label: 'Seychelles', value: 'Seychelles' },
    { label: 'Singapura', value: 'Singapura' },
    { label: 'Síria', value: 'Síria' },
    { label: 'Sri Lanka', value: 'Sri Lanka' },
    { label: 'St. Kitts & Nevis', value: 'St. Kitts & Nevis' },
    { label: 'St. Lúcia', value: 'St. Lúcia' },
    { label: 'St. Vincent', value: 'St. Vincent' },
    { label: 'Sudão', value: 'Sudão' },
    { label: 'Suécia', value: 'Suécia' },
    { label: 'Suiça', value: 'Suiça' },
    { label: 'Suriname', value: 'Suriname' },
    { label: 'Tailândia', value: 'Tailândia' },
    { label: 'Taiwan', value: 'Taiwan' },
    { label: 'Tanzânia', value: 'Tanzânia' },
    { label: 'Togo', value: 'Togo' },
    { label: 'Trinidad & Tobago', value: 'Trinidad & Tobago' },
    { label: 'Tunísia', value: 'Tunísia' },
    { label: 'Turquia', value: 'Turquia' },
    { label: 'Ucrânia', value: 'Ucrânia' },
    { label: 'Uganda', value: 'Uganda' },
    { label: 'Uruguai', value: 'Uruguai' },
    { label: 'Venezuela', value: 'Venezuela' },
    { label: 'Vietnã', value: 'Vietnã' },
    { label: 'Zaire', value: 'Zaire' },
    { label: 'Zâmbia', value: 'Zâmbia' },
    { label: 'Zimbábue', value: 'Zimbábue' },
];